apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prom-monitoring-flask-app
spec:  
  endpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: 1s
  selector:
    matchLabels:
      app: flask-monitoring